### ISSUE TITLE
The example code turns on the front camera by default. How to start the back camera?

### ISSUE THREAD

**Issue by supergf** [livekit/client-sdk-android#454]
I used livekit 2.2.0，the codes is from sample app-basic。
But The example code turns on the front camera. How should I turn on the back camera?

**Comment by davidliu** [comment]
If you want to start with the back camera instead of the front, you can change the defaults:

```
    val room = LiveKit.create(
        appContext = application,
        options = RoomOptions(
            videoTrackCaptureDefaults = LocalVideoTrackOptions(
                position = CameraPosition.BACK
            )
        ),
    )
```

If you want to switch the camera mid-capture, you can use `videoTrack.switchCamera(position = newPosition)`.

Look at the CallViewModel in `sample-app-common`. The basic app is kept as simple as possible to get people up and running.
